[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#3b82f6"
backgroundColor = "#070d19"
secondaryBackgroundColor = "#101a30"
textColor = "#e2e8f0"

[server]
runOnSave = false
enableCORS = false
enableXsrfProtection = false


